#pragma once

#define ACHIEVEMENT_LIST \
    X(ACHIEVEMENT_MANIFEST_DESTINY, "ACHIEVEMENT_MANIFEST_DESTINY") \
    X(ACHIEVEMENT_HIGH_NOON, "ACHIEVEMENT_HIGH_NOON") \
    X(ACHIEVEMENT_MAXED_OUT, "ACHIEVEMENT_MAXED_OUT") \
    X(ACHIEVEMENT_BEST_OF_THE_BEST, "ACHIEVEMENT_BEST_OF_THE_BEST") \
    X(ACHIEVEMENT_RAGTAG_OUTFIT, "ACHIEVEMENT_RAGTAG_OUTFIT") \
    X(ACHIEVEMENT_ARSONIST, "ACHIEVEMENT_ARSONIST") \
    X(ACHIEVEMENT_DRIVE_BY_SHOOTING, "ACHIEVEMENT_DRIVE_BY_SHOOTING") \
    X(ACHIEVEMENT_GREEDY_OPENER, "ACHIEVEMENT_GREEDY_OPENER") \
    X(ACHIEVEMENT_UNDERCOVER, "ACHIEVEMENT_UNDERCOVER") \
    X(ACHIEVEMENT_SPECIAL_DELIVERY, "ACHIEVEMENT_SPECIAL_DELIVERY") \
    X(ACHIEVEMENT_CLAIM_JUMPER, "ACHIEVEMENT_CLAIM_JUMPER") \
    X(ACHIEVEMENT_HOLD_YOUR_HORSES, "ACHIEVEMENT_HOLD_YOUR_HORSES") \
    X(ACHIEVEMENT_EXPANSION_DENIED, "ACHIEVEMENT_EXPANSION_DENIED") \
    X(ACHIEVEMENT_MINESWEEPER, "ACHIEVEMENT_MINESWEEPER") \
    X(ACHIEVEMENT_MIND_YOUR_STEP, "ACHIEVEMENT_MIND_YOUR_STEP") \
    X(ACHIEVEMENT_BUNKER_BUSTER, "ACHIEVEMENT_BUNKER_BUSTER") \

enum Achievement {
#define X(name, str) name,
    ACHIEVEMENT_LIST
#undef X
    ACHIEVEMENT_COUNT
};

void achievement_grant(Achievement achievement);
