#pragma once

#define ANIMATION_LOOPS_INDEFINITELY -1

#include "util/math.h"

enum AnimationName {
    ANIMATION_UI_MOVE_CELL,
    ANIMATION_UI_MOVE_ENTITY,
    ANIMATION_UI_HIGHLIGHT_ENTITY,
    ANIMATION_UI_MOVE_ATTACK_ENTITY,
    ANIMATION_UNIT_IDLE,
    ANIMATION_UNIT_MOVE,
    ANIMATION_UNIT_MOVE_SLOW,
    ANIMATION_UNIT_MOVE_CANNON,
    ANIMATION_UNIT_ATTACK,
    ANIMATION_SOLDIER_RANGED_ATTACK,
    ANIMATION_SOLDIER_CHARGE,
    ANIMATION_CANNON_ATTACK,
    ANIMATION_UNIT_MINE,
    ANIMATION_UNIT_BUILD,
    ANIMATION_UNIT_DEATH,
    ANIMATION_UNIT_DEATH_FADE,
    ANIMATION_CANNON_DEATH,
    ANIMATION_CANNON_DEATH_FADE,
    ANIMATION_BALLOON_MOVE,
    ANIMATION_BALLOON_DEATH_START,
    ANIMATION_BALLOON_DEATH,
    ANIMATION_BALLOON_DEATH_FADE,
    ANIMATION_RALLY_FLAG,
    ANIMATION_PARTICLE_SPARKS,
    ANIMATION_PARTICLE_BUNKER_COWBOY,
    ANIMATION_PARTICLE_EXPLOSION,
    ANIMATION_PARTICLE_CANNON_EXPLOSION,
    ANIMATION_PARTICLE_BLEED,
    ANIMATION_PARTICLE_AVALANCHE,
    ANIMATION_SMITH_BEGIN,
    ANIMATION_SMITH_LOOP,
    ANIMATION_SMITH_END,
    ANIMATION_WORKSHOP,
    ANIMATION_FIRE_START,
    ANIMATION_FIRE_BURN,
    ANIMATION_MINE_PRIME,
    ANIMATION_NAME_COUNT
};

struct Animation {
    AnimationName name;
    uint32_t timer;
    uint32_t frame_index;
    ivec2 frame;
    int loops_remaining = 0;
};

// Initializes the animation data
void animation_init();
Animation animation_create(AnimationName name);
bool animation_is_playing(const Animation& animation);
void animation_update(Animation& animation);
void animation_stop(Animation& animation);
