#pragma once

#include <cstddef>

#define RESOURCE_INDEX_FILE_PATH "res.idx"
#define RESOURCE_PACK_FILE_PATH "res.pak"
#define RESOURCE_INDEX_FILE_SIGNATURE 0x77234639
#define RESOURCE_PACK_FILE_SIGNATURE 0x77237225

#define RESOURCE_LIST \
    X(RESOURCE_FONT_HACK, "font/hack.ttf") \
    X(RESOURCE_FONT_WESTERN, "font/western.ttf") \
    X(RESOURCE_FONT_M3X6, "font/m3x6.ttf") \
    X(RESOURCE_SHADER_SCREEN_VERT, "shader/screen.vert.glsl") \
    X(RESOURCE_SHADER_SCREEN_FRAG, "shader/screen.frag.glsl") \
    X(RESOURCE_SHADER_SPRITE_VERT, "shader/sprite.vert.glsl") \
    X(RESOURCE_SHADER_SPRITE_FRAG, "shader/sprite.frag.glsl") \
    X(RESOURCE_SHADER_MINIMAP_VERT, "shader/minimap.vert.glsl") \
    X(RESOURCE_SHADER_MINIMAP_FRAG, "shader/minimap.frag.glsl") \
    X(RESOURCE_CURSOR_DEFAULT, "sprite/cursor/default.png") \
    X(RESOURCE_CURSOR_TARGET, "sprite/cursor/target.png") \
    X(RESOURCE_TILESET_ARIZONA, "sprite/map/arizona_tiles.png") \
    X(RESOURCE_TILESET_BOULDER, "sprite/map/boulder_tiles.png") \
    X(RESOURCE_TILESET_KLONDIKE, "sprite/map/klondike_tiles.png") \
    X(RESOURCE_TILESET_FOG, "sprite/map/fog_of_war.png") \
    X(RESOURCE_SPRITE_DECORATIONS_ARIZONA, "sprite/map/arizona_decorations.png") \
    X(RESOURCE_SPRITE_DECORATIONS_BOULDER, "sprite/map/boulder_decorations.png") \
    X(RESOURCE_SPRITE_DECORATIONS_KLONDIKE, "sprite/map/klondike_decorations.png") \
    X(RESOURCE_SPRITE_UI_MINIMAP, "sprite/ui/minimap.png") \
    X(RESOURCE_SPRITE_UI_WANTED_SIGN, "sprite/ui/wanted_sign.png") \
    X(RESOURCE_SPRITE_UI_FRAME_BOLTS, "sprite/ui/frame_bolts.png") \
    X(RESOURCE_SPRITE_UI_FRAME, "sprite/ui/frame.png") \
    X(RESOURCE_SPRITE_UI_FRAME_SMALL, "sprite/ui/frame_small.png") \
    X(RESOURCE_SPRITE_UI_BUTTON_REFRESH, "sprite/ui/menu_refresh.png") \
    X(RESOURCE_SPRITE_UI_BUTTON_ARROW, "sprite/ui/menu_next.png") \
    X(RESOURCE_SPRITE_UI_BUTTON_BURGER, "sprite/ui/menu_burger.png") \
    X(RESOURCE_SPRITE_UI_BUTTON_PROFILE, "sprite/ui/menu_profile.png") \
    X(RESOURCE_SPRITE_UI_REPLAY_PAUSE, "sprite/ui/replay_pause.png") \
    X(RESOURCE_SPRITE_UI_REPLAY_PLAY, "sprite/ui/replay_play.png") \
    X(RESOURCE_SPRITE_UI_EDITOR_PLUS, "sprite/ui/editor_plus.png") \
    X(RESOURCE_SPRITE_UI_EDITOR_EDIT, "sprite/ui/editor_edit.png") \
    X(RESOURCE_SPRITE_UI_EDITOR_TRASH, "sprite/ui/editor_trash.png") \
    X(RESOURCE_SPRITE_UI_GOLD_ICON, "sprite/ui/icon_gold.png") \
    X(RESOURCE_SPRITE_UI_HOUSE_ICON, "sprite/ui/icon_house.png") \
    X(RESOURCE_SPRITE_UI_MINER_ICON, "sprite/ui/icon_miner.png") \
    X(RESOURCE_SPRITE_UI_ENERGY_ICON, "sprite/ui/icon_energy.png") \
    X(RESOURCE_SPRITE_UI_DROPDOWN, "sprite/ui/options_dropdown.png") \
    X(RESOURCE_SPRITE_UI_DROPDOWN_MINI, "sprite/ui/dropdown_mini.png") \
    X(RESOURCE_SPRITE_UI_TEAM_PICKER, "sprite/ui/team_picker.png") \
    X(RESOURCE_SPRITE_UI_MENU_BUTTON, "sprite/ui/parchment_buttons.png") \
    X(RESOURCE_SPRITE_UI_TEXT_FRAME, "sprite/ui/text_frame.png") \
    X(RESOURCE_SPRITE_UI_CLOUDS, "sprite/ui/menu_clouds.png") \
    X(RESOURCE_SPRITE_UI_TITLE, "sprite/ui/title.png") \
    X(RESOURCE_SPRITE_UI_MOVE, "sprite/select_ring/move.png") \
    X(RESOURCE_SPRITE_UI_CONTROL_GROUP, "sprite/ui/control_group_frame.png") \
    X(RESOURCE_SPRITE_UI_ICON_BUTTON, "sprite/icon_button/button.png") \
    X(RESOURCE_SPRITE_UI_TOOLTIP_FRAME, "sprite/ui/tooltip_frame.png") \
    X(RESOURCE_SPRITE_UI_STAT_ICON_DETECTION, "sprite/ui/icon_detection.png") \
    X(RESOURCE_SPRITE_UI_OBJECTIVE_CHECKBOX, "sprite/ui/objective_checkbox.png") \
    X(RESOURCE_SPRITE_UI_CAMPAIGN_MAP, "sprite/ui/campaign_map.png") \
    X(RESOURCE_SPRITE_UI_CAMPAIGN_SCENARIO_ORB_BLUE, "sprite/ui/campaign_mission_blue.png") \
    X(RESOURCE_SPRITE_UI_CAMPAIGN_SCENARIO_ORB_GREEN, "sprite/ui/campaign_mission_green.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_ATTACK, "sprite/icon_button/attack.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_STOP, "sprite/icon_button/stop.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_DEFEND, "sprite/icon_button/defend.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_BUILD, "sprite/icon_button/build.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_BUILD2, "sprite/icon_button/build2.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_REPAIR, "sprite/icon_button/repair.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_UNLOAD, "sprite/icon_button/unload.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_CANCEL, "sprite/icon_button/cancel.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_EXPLODE, "sprite/icon_button/explode.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_HALL, "sprite/icon_button/hall.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_HOUSE, "sprite/icon_button/house.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_SALOON, "sprite/icon_button/saloon.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_BUNKER, "sprite/icon_button/bunker.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_SMITH, "sprite/icon_button/smith.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_COOP, "sprite/icon_button/coop.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_BARRACKS, "sprite/icon_button/barracks.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_SHERIFFS, "sprite/icon_button/sheriffs.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_MINER, "sprite/icon_button/miner.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_WAGON, "sprite/icon_button/wagon.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_WAR_WAGON, "sprite/icon_button/war_wagon.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_COWBOY, "sprite/icon_button/cowboy.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_BANDIT, "sprite/icon_button/bandit.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_SAPPER, "sprite/icon_button/sapper.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_PYRO, "sprite/icon_button/pyro.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_SOLDIER, "sprite/icon_button/soldier.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_CANNON, "sprite/icon_button/cannon.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_JOCKEY, "sprite/icon_button/jockey.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_DETECTIVE, "sprite/icon_button/detective.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_BALLOON, "sprite/icon_button/balloon.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_LANDMINE, "sprite/icon_button/landmine.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_GOLDMINE, "sprite/icon_button/goldmine.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_WAGON_ARMOR, "sprite/icon_button/wagon_armor.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_WORKSHOP, "sprite/icon_button/workshop.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_BAYONETS, "sprite/icon_button/bayonets.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_MOLOTOV, "sprite/icon_button/molotov.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_CAMO, "sprite/icon_button/camo.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_DECAMO, "sprite/icon_button/camo_off.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_PRIVATE_EYE, "sprite/icon_button/private_eye.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_GETAWAY_BOOTS, "sprite/icon_button/getaway_boots.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_IRON_SIGHTS, "sprite/icon_button/iron_sights.png") \
    X(RESOURCE_SPRITE_BUTTON_ICON_CRATE, "sprite/icon_button/crate.png") \
    X(RESOURCE_SPRITE_SELECT_RING_LANDMINE, "sprite/select_ring/landmine.png") \
    X(RESOURCE_SPRITE_SELECT_RING_LANDMINE_ATTACK, "sprite/select_ring/landmine_attack.png") \
    X(RESOURCE_SPRITE_SELECT_RING_UNIT, "sprite/select_ring/1x1.png") \
    X(RESOURCE_SPRITE_SELECT_RING_UNIT_ATTACK, "sprite/select_ring/1x1_attack.png") \
    X(RESOURCE_SPRITE_SELECT_RING_WAGON, "sprite/select_ring/wagon.png") \
    X(RESOURCE_SPRITE_SELECT_RING_WAGON_ATTACK, "sprite/select_ring/wagon_attack.png") \
    X(RESOURCE_SPRITE_SELECT_RING_BUILDING_SIZE2, "sprite/select_ring/2x2.png") \
    X(RESOURCE_SPRITE_SELECT_RING_BUILDING_SIZE2_ATTACK, "sprite/select_ring/2x2_attack.png") \
    X(RESOURCE_SPRITE_SELECT_RING_BUILDING_SIZE3, "sprite/select_ring/3x3.png") \
    X(RESOURCE_SPRITE_SELECT_RING_BUILDING_SIZE3_ATTACK, "sprite/select_ring/3x3_attack.png") \
    X(RESOURCE_SPRITE_SELECT_RING_BUILDING_SIZE4, "sprite/select_ring/4x4.png") \
    X(RESOURCE_SPRITE_SELECT_RING_BUILDING_SIZE4_ATTACK, "sprite/select_ring/4x4_attack.png") \
    X(RESOURCE_SPRITE_SELECT_RING_GOLDMINE, "sprite/select_ring/goldmine.png") \
    X(RESOURCE_SPRITE_SELECT_RING_CRATE, "sprite/select_ring/crate.png") \
    X(RESOURCE_SPRITE_GOLDMINE, "sprite/entity/goldmine.png") \
    X(RESOURCE_SPRITE_CRATE, "sprite/entity/crate.png") \
    X(RESOURCE_SPRITE_SWITCH, "sprite/entity/switch.png") \
    X(RESOURCE_SPRITE_UNIT_WAGON, "sprite/entity/unit_wagon.png") \
    X(RESOURCE_SPRITE_UNIT_WAR_WAGON, "sprite/entity/unit_war_wagon.png") \
    X(RESOURCE_SPRITE_UNIT_MINER, "sprite/entity/unit_miner.png") \
    X(RESOURCE_SPRITE_UNIT_COWBOY, "sprite/entity/unit_cowboy.png") \
    X(RESOURCE_SPRITE_UNIT_SAPPER, "sprite/entity/unit_sapper.png") \
    X(RESOURCE_SPRITE_UNIT_PYRO, "sprite/entity/unit_pyro.png") \
    X(RESOURCE_SPRITE_UNIT_JOCKEY, "sprite/entity/unit_jockey.png") \
    X(RESOURCE_SPRITE_UNIT_SOLDIER, "sprite/entity/unit_soldier.png") \
    X(RESOURCE_SPRITE_UNIT_CANNON, "sprite/entity/unit_cannon.png") \
    X(RESOURCE_SPRITE_UNIT_DETECTIVE, "sprite/entity/unit_spy.png") \
    X(RESOURCE_SPRITE_UNIT_BALLOON, "sprite/entity/unit_balloon.png") \
    X(RESOURCE_SPRITE_UNIT_BALLOON_STEAM, "sprite/entity/unit_balloon_steam.png") \
    X(RESOURCE_SPRITE_UNIT_BALLOON_SHADOW, "sprite/entity/unit_balloon_shadow.png") \
    X(RESOURCE_SPRITE_UNIT_BANDIT, "sprite/entity/unit_bandit.png") \
    X(RESOURCE_SPRITE_MINER_BUILDING, "sprite/entity/unit_miner_building.png") \
    X(RESOURCE_SPRITE_BUILDING_HALL, "sprite/entity/building_hall.png") \
    X(RESOURCE_SPRITE_BUILDING_HOUSE, "sprite/entity/building_house.png") \
    X(RESOURCE_SPRITE_BUILDING_SALOON, "sprite/entity/building_saloon.png") \
    X(RESOURCE_SPRITE_BUILDING_BUNKER, "sprite/entity/building_bunker.png") \
    X(RESOURCE_SPRITE_BUILDING_SMITH, "sprite/entity/building_smith.png") \
    X(RESOURCE_SPRITE_BUILDING_SMITH_ANIMATION, "sprite/entity/building_smith_animation.png") \
    X(RESOURCE_SPRITE_BUILDING_WORKSHOP, "sprite/entity/building_workshop.png") \
    X(RESOURCE_SPRITE_BUILDING_COOP, "sprite/entity/building_coop.png") \
    X(RESOURCE_SPRITE_BUILDING_BARRACKS, "sprite/entity/building_barracks.png") \
    X(RESOURCE_SPRITE_BUILDING_SHERIFFS, "sprite/entity/building_sheriffs.png") \
    X(RESOURCE_SPRITE_BUILDING_LANDMINE, "sprite/entity/building_mine.png") \
    X(RESOURCE_SPRITE_BUILDING_DESTROYED_BUNKER, "sprite/entity/building_destroyed_bunker.png") \
    X(RESOURCE_SPRITE_BUILDING_DESTROYED_MINE, "sprite/entity/building_destroyed_mine.png") \
    X(RESOURCE_SPRITE_BUILDING_DESTROYED_2, "sprite/entity/building_destroyed2x2.png") \
    X(RESOURCE_SPRITE_BUILDING_DESTROYED_3, "sprite/entity/building_destroyed3x3.png") \
    X(RESOURCE_SPRITE_BUILDING_DESTROYED_4, "sprite/entity/building_destroyed4x4.png") \
    X(RESOURCE_SPRITE_RALLY_FLAG, "sprite/rally_flag.png") \
    X(RESOURCE_SPRITE_PARTICLE_SPARKS, "sprite/particle/sparks.png") \
    X(RESOURCE_SPRITE_PARTICLE_BUNKER_FIRE, "sprite/particle/bunker_cowboy.png") \
    X(RESOURCE_SPRITE_PARTICLE_EXPLOSION, "sprite/particle/explosion.png") \
    X(RESOURCE_SPRITE_PARTICLE_CANNON_EXPLOSION, "sprite/particle/cannon_explosion.png") \
    X(RESOURCE_SPRITE_PARTICLE_FIRE, "sprite/particle/fire.png") \
    X(RESOURCE_SPRITE_PARTICLE_AVALANCHE, "sprite/particle/avalanche.png") \
    X(RESOURCE_SPRITE_PROJECTILE_MOLOTOV, "sprite/projectile_molotov.png") \
    X(RESOURCE_SPRITE_WORKSHOP_STEAM, "sprite/entity/building_workshop_steam.png") \
    X(RESOURCE_DATA_CAMPAIGN_ROADS, "sprite/ui/roads.dat") \
    X(RESOURCE_SOUND_UI_CLICK, "sfx/ui_click.wav") \
    X(RESOURCE_SOUND_DEATH1, "sfx/death1.wav") \
    X(RESOURCE_SOUND_DEATH2, "sfx/death2.wav") \
    X(RESOURCE_SOUND_DEATH3, "sfx/death3.wav") \
    X(RESOURCE_SOUND_DEATH4, "sfx/death4.wav") \
    X(RESOURCE_SOUND_DEATH5, "sfx/death5.wav") \
    X(RESOURCE_SOUND_DEATH6, "sfx/death6.wav") \
    X(RESOURCE_SOUND_DEATH7, "sfx/death7.wav") \
    X(RESOURCE_SOUND_DEATH8, "sfx/death8.wav") \
    X(RESOURCE_SOUND_DEATH9, "sfx/death9.wav") \
    X(RESOURCE_SOUND_MUSKET1, "sfx/musket1.wav") \
    X(RESOURCE_SOUND_MUSKET2, "sfx/musket2.wav") \
    X(RESOURCE_SOUND_MUSKET3, "sfx/musket3.wav") \
    X(RESOURCE_SOUND_MUSKET4, "sfx/musket4.wav") \
    X(RESOURCE_SOUND_MUSKET5, "sfx/musket5.wav") \
    X(RESOURCE_SOUND_MUSKET6, "sfx/musket6.wav") \
    X(RESOURCE_SOUND_MUSKET7, "sfx/musket7.wav") \
    X(RESOURCE_SOUND_MUSKET8, "sfx/musket8.wav") \
    X(RESOURCE_SOUND_MUSKET9, "sfx/musket9.wav") \
    X(RESOURCE_SOUND_GUN1, "sfx/gun1.wav") \
    X(RESOURCE_SOUND_GUN2, "sfx/gun2.wav") \
    X(RESOURCE_SOUND_GUN3, "sfx/gun3.wav") \
    X(RESOURCE_SOUND_GUN4, "sfx/gun4.wav") \
    X(RESOURCE_SOUND_GUN5, "sfx/gun5.wav") \
    X(RESOURCE_SOUND_EXPLOSION1, "sfx/explosion1.wav") \
    X(RESOURCE_SOUND_EXPLOSION2, "sfx/explosion2.wav") \
    X(RESOURCE_SOUND_EXPLOSION3, "sfx/explosion3.wav") \
    X(RESOURCE_SOUND_EXPLOSION4, "sfx/explosion4.wav") \
    X(RESOURCE_SOUND_PICKAXE1, "sfx/pickaxe1.wav") \
    X(RESOURCE_SOUND_PICKAXE2, "sfx/pickaxe2.wav") \
    X(RESOURCE_SOUND_PICKAXE3, "sfx/pickaxe3.wav") \
    X(RESOURCE_SOUND_HAMMER1, "sfx/hammer1.wav") \
    X(RESOURCE_SOUND_HAMMER2, "sfx/hammer2.wav") \
    X(RESOURCE_SOUND_HAMMER3, "sfx/hammer3.wav") \
    X(RESOURCE_SOUND_HAMMER4, "sfx/hammer4.wav") \
    X(RESOURCE_SOUND_BUILDING_PLACE, "sfx/building_place.wav") \
    X(RESOURCE_SOUND_SWORD1, "sfx/sword1.wav") \
    X(RESOURCE_SOUND_SWORD2, "sfx/sword2.wav") \
    X(RESOURCE_SOUND_SWORD3, "sfx/sword3.wav") \
    X(RESOURCE_SOUND_DEATH_CHICKEN1, "sfx/death_chicken1.wav") \
    X(RESOURCE_SOUND_DEATH_CHICKEN2, "sfx/death_chicken2.wav") \
    X(RESOURCE_SOUND_DEATH_CHICKEN3, "sfx/death_chicken3.wav") \
    X(RESOURCE_SOUND_DEATH_CHICKEN4, "sfx/death_chicken4.wav") \
    X(RESOURCE_SOUND_CANNON1, "sfx/cannon1.wav") \
    X(RESOURCE_SOUND_CANNON2, "sfx/cannon2.wav") \
    X(RESOURCE_SOUND_CANNON3, "sfx/cannon3.wav") \
    X(RESOURCE_SOUND_CANNON4, "sfx/cannon4.wav") \
    X(RESOURCE_SOUND_BUILDING_DESTROY, "sfx/building_destroy.wav") \
    X(RESOURCE_SOUND_BUNKER_DESTROY, "sfx/bunker_destroy.wav") \
    X(RESOURCE_SOUND_MINE_DESTROY, "sfx/mine_destroy.wav") \
    X(RESOURCE_SOUND_MINE_INSERT, "sfx/mine_insert.wav") \
    X(RESOURCE_SOUND_MINE_PRIME, "sfx/mine_prime.wav") \
    X(RESOURCE_SOUND_THROW, "sfx/throw.wav") \
    X(RESOURCE_SOUND_FLAG_THUMP, "sfx/flag_thump.wav") \
    X(RESOURCE_SOUND_GARRISON_IN, "sfx/garrison_in.wav") \
    X(RESOURCE_SOUND_GARRISON_OUT, "sfx/garrison_out.wav") \
    X(RESOURCE_SOUND_ALERT_BELL, "sfx/alert_bell.wav") \
    X(RESOURCE_SOUND_ALERT_BUILDING, "sfx/alert_building.wav") \
    X(RESOURCE_SOUND_ALERT_RESEARCH, "sfx/alert_research.wav") \
    X(RESOURCE_SOUND_ALERT_UNIT, "sfx/alert_unit.wav") \
    X(RESOURCE_SOUND_GOLD_MINE_COLLAPSE, "sfx/gold_mine_collapse.wav") \
    X(RESOURCE_SOUND_MOLOTOV_IMPACT, "sfx/molotov_impact.wav") \
    X(RESOURCE_SOUND_FIRE_BURN, "sfx/fire_burn.wav") \
    X(RESOURCE_SOUND_PISTOL_SILENCED1, "sfx/pistol_silenced1.wav") \
    X(RESOURCE_SOUND_PISTOL_SILENCED2, "sfx/pistol_silenced2.wav") \
    X(RESOURCE_SOUND_PISTOL_SILENCED3, "sfx/pistol_silenced3.wav") \
    X(RESOURCE_SOUND_CAMO_ON, "sfx/camo_on.wav") \
    X(RESOURCE_SOUND_CAMO_OFF, "sfx/camo_off.wav") \
    X(RESOURCE_SOUND_BALLOON_DEATH, "sfx/balloon_death.wav") \
    X(RESOURCE_SOUND_RICOCHET1, "sfx/ricochet1.wav") \
    X(RESOURCE_SOUND_RICOCHET2, "sfx/ricochet2.wav") \
    X(RESOURCE_SOUND_RICOCHET3, "sfx/ricochet3.wav") \
    X(RESOURCE_SOUND_RICOCHET4, "sfx/ricochet4.wav") \
    X(RESOURCE_SOUND_RICOCHET5, "sfx/ricochet5.wav") \
    X(RESOURCE_SOUND_OBJECTIVE_COMPLETE, "sfx/objective_complete.wav") \
    X(RESOURCE_SOUND_MATCH_START, "sfx/match_start.wav") \
    X(RESOURCE_SOUND_GOLD_PICKUP, "sfx/gold_pickup.wav") \
    X(RESOURCE_SOUND_AVALANCHE, "sfx/avalanche.wav") \
    X(RESOURCE_SOUND_PEN_SCRATCH, "sfx/pen_scratch.wav") \
    X(RESOURCE_SOUND_STINGER_VICTORY, "sfx/stinger_victory.wav") \
    X(RESOURCE_SOUND_STINGER_DEFEAT, "sfx/stinger_defeat.wav") \
    X(RESOURCE_MUSIC_MENU, "music/menu.ogg") \
    X(RESOURCE_MUSIC_MATCH1, "music/match1.ogg") \
    X(RESOURCE_MUSIC_MATCH2, "music/match2.ogg") \
    X(RESOURCE_MUSIC_MATCH3, "music/match3.ogg") \
    X(RESOURCE_MUSIC_MATCH4, "music/match4.ogg") \
    X(RESOURCE_MUSIC_MATCH5, "music/match5.ogg") \
    X(RESOURCE_CREDITS, "credits.txt") \

enum ResourceName {
#define X(name, path) name,
    RESOURCE_LIST
#undef X
    RESOURCE_COUNT
};

struct ResourceIndexEntry {
    size_t offset;
    size_t size;
};

const char* resource_get_path(ResourceName resource);
bool resource_is_text(ResourceName resource);
